'use client'

import { ParsedHtml } from '@/lib/utils/Functions'
import { TypeProject } from '@/lib/utils/Types'
import React, { FormEvent, useState } from 'react'
import { BiExpand, BiX } from 'react-icons/bi'

type SiteGeneratorModelProps = {
  isOpen: boolean;
  handleToggleModel: () => void;
};

const SiteGeneratorModel: React.FC<SiteGeneratorModelProps> = ({ isOpen, handleToggleModel }) => {
  // Rest of the component code

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');

  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    handleToggleModel()

  };

  const toggleModel = () => {
    handleToggleModel()
    if (!isOpen) {
      document.body.style.overflow = 'hidden' // Apply the CSS style to hide scrolling
    } else {
      document.body.style.overflow = '' // Reset the CSS style to restore scrolling
    }
  }

  return (
    <>
      <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-opacity-50 backdrop-blur z-50">
        <div className='w-[95%] sm:w-[85%] md:w-[70%] lg:w-[60%] xl:[50%] max-h-[85vh] overflow-auto mx-auto bg-primarybg border p-4 flex flex-col rounded-md drop-shadow-sm'>

          {/* Documentation */}
          <h2 className="text-2xl font-bold mb-4">Static HTML Page Generator</h2>
          <p>Welcome to the Static HTML Page Generator! This tool allows you to create a static HTML page that can be hosted on your own website or elsewhere. Please read the following information before using the form.</p>

          <ol className="list-decimal mt-4 pl-6">
            <li>
              <strong>Your Data Can Be Used Somewhere Else:</strong> The information you provide in the form can be used to generate the static HTML page. Make sure to fill in the data accurately for the best outcome.
            </li>
            <li>
              <strong>Ugly Domain:</strong> If you choose to host the generated HTML page on this platform, please note that you will be assigned an autogenerated domain. It may not have an aesthetically pleasing name, but you have the option to host it elsewhere for a custom domain.
            </li>
            <li>
              <strong>Fill the Data Correctly:</strong> To ensure the best outcome, please fill in the data accurately. Double-check the information you provide, such as URLs, images, and text content.
            </li>
            <li>
              <strong>Not Owned by Any Organization:</strong> This Static HTML Page Generator is a free and open-source tool. It is not owned or affiliated with any specific organization. The generated code is solely your property, and you are responsible for its usage and hosting.
            </li>
          </ol>

          <p className="mt-4">Before generating the HTML page, please complete the following:</p>

          {/* Form */}
          <form onSubmit={handleSubmit} className="mt-4">
            <div>
              <input
                type="checkbox"
                id="terms"
                required
                className="mr-2"
              />
              <span className="text-sm">I accept the Terms and Conditions.</span>
            </div>
            <div>
              <input
                type="checkbox"
                id="privacy"
                required
                className="mr-2"
              />
              <span className="text-sm">I have read the Privacy Policy.</span>
            </div>
            <button type='submit' className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">
              Generate HTML Page
            </button>
          </form>

        </div>
      </div>

    </>
  )
}

export default SiteGeneratorModel
